### ISSUE TITLE
Bias mitigation and fairness boosting in multi class classification use case

### ISSUE THREAD

**Issue by pradeepdev-1995** [ResponsiblyAI/responsibly#65]
Is it support mitigating bias and improving fairness in multi-class classification problems?
If so please provide an example of doing the same in a sample multi-class classification dataset.

**Comment by shlomihod** [comment]
Unfortunately `responsibly` currently does not support multiclass classification. Perhaps the `fairlearn` could be helpful:
https://fairlearn.org/v0.8/auto_examples/plot_metricframe_beyond_binary_classification.html

**Comment by pradeepdev-1995** [comment]
@shlomihod Thank you. Let me check it.
